enum actionTypes {
  CLICK_NUMBER = "CLICK_NUMBER",
  CLEAR = "CLEAR",
  CLICK_DECIMAL = "CLICK_DECIMAL",
  CLICK_EXPRESSION = "CLICK_EXPRESSION",
  EVALUATE = "EVALUATE",
  CLICK_OPERATION = "CLICK_OPERATION"
}

export default actionTypes;