enum actionTypes {
  CLICK_NUMBER = "CLICK_NUMBER",
  CLEAR = "CLEAR",
  CLICK_DECIMAL = "CLICK_DECIMAL",
  CLICK_EXPRESSION = "CLICK_EXPRESSION",
  EVALUATE = "EVALUATE",
  CLICK_OPERATION = "CLICK_OPERATION",
  CLICK_SPECIAL = "CLICK_SPECIAL",
  CLICK_INVERSE = "CLICK_INVERSE",
  CLICK_RANDOM = "CLICK_RANDOM",
  CHANGE_ANGLE = "CHANGE_ANGLE"
}

export default actionTypes;